server:
  port: ${APP_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRE_SQL_DB_HOST:localhost}:${POSTGRE_SQL_DB_PORT:5432}/${POSTGRE_SQL_DB_NAME:mydatabase}
    username: ${POSTGRE_SQL_DB_USERNAME:myuser}
    password: ${POSTGRE_SQL_DB_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}