# Internal Application Configuration Section
server:
  port: ${APP_PORT:8080}

management:
  server:
    port: ${APP_PORT:8080}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ["health", "info", "metrics", "env"]
  health:
    db:
      enabled: false

security:
  csrf:
    enabled: ${CSRF_ENABLE:false}

# External System Configuration Section
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${POSTGRE_SQL_DB_HOST:localhost}:${POSTGRE_SQL_DB_PORT:5432}/${POSTGRE_SQL_DB_NAME:mydatabase}
    username: ${POSTGRE_SQL_DB_USERNAME:myuser}
    password: ${POSTGRE_SQL_DB_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      maxLifetime: 30000
      idleTimeout: 10000
      connection-timeout: 2000
      validation-timeout: 1000

db:
  dbHostSource: ${POSTGRE_SQL_DB_HOST:localhost}
  dbPort: ${POSTGRE_SQL_DB_PORT:5432}
  dbName: ${POSTGRE_SQL_DB_NAME:mydatabase}

# Secrets Section
app:
  jwt-secret: DummySecretKeyWhichIsAtLeast32CharactersLong
