name: QA Workflow Services

on:
  workflow_dispatch:
  # Any feature branch PR to QA or direct push to QA will trigger this workflow
  pull_request:
    types:
      - opened       # Only when PR is first opened
    branches:
      - qa           # Target branch (base) must be QA
  push:
    branches:
      - 'qa'

run-name: "[QA]: ${{ github.event.head_commit.message }}  (event ${{ github.event_name }} at ${{ github.sha }})"

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.determine.outputs.environment }}
    steps:
      - id: determine
        name: Set environment to QA
        run: |
          echo "environment=QA" >> $GITHUB_OUTPUT
          echo "The matching deployment's environment is QA"

  call-service-workflow:
    needs: set-environment
    uses: Le-Hoang-Thinh-The-Automationist/pfh-pipeline/.github/workflows/service-workflow.yml@main
    with:
      # Mandatory inputs
      environment: ${{ needs.set-environment.outputs.environment }}
      service-name: pfh-user-service

      # Custom
      custom-test-script: ./services-functionaliy-test.sh -t unit
      custom-build-script: services-functionaliy-test.sh -t int
