name: Developer Workflow Services

on:
  workflow_dispatch:
    inputs:
      # ============ INPUT CONFIGURATION ============
      # Choose brach or commit to run fast-feedback CI
      fast-feed-back-type:
        description: Choose the branch or commit to run fast-feedback CI
        required: true
        type: choice
        options:
          - branch
          - commit
      identifier:
        description: The identifier of the branch or commit to run fast-feedback CI
        required: true
        type: string
      # Choose the service to run fast-feedback CI
      service-name:
        description: Name of the service to run fast-feedback CI
        required: true
        type: string

  push:
    # Any branch except main, prod, stag, qa will trigger this workflow
    branches-ignore:
      - 'main'
      - 'prod'
      - 'stag'
      - 'qa'

run-name: "[DEV] ${{ github.ref_name }}: (${{ github.sha }})"

jobs:
  set-configuration:
    name: Setup configuration based on the trigger event
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.determine.outputs.environment }}
    steps:
      - id: determine
        name: Set environment to DEV
        run: |
          echo "environment=DEV" >> $GITHUB_OUTPUT
          echo "The matching deployment's environment is DEV"  

  # This job will run if it's a PR event or if the specified branch has an open PR to QA when triggered manually
  call-fast-feedback-ci-workflow:
    needs: set-configuration
    # Only run this job if it's a PR event or if the specified branch has an open PR to QA when triggered manually
    uses: Le-Hoang-Thinh-The-Automationist/pfh-pipeline/.github/workflows/DEV_commit-fast-feedback.yml@main
    with:
      # Mandatory inputs
      environment: ${{ needs.set-environment.outputs.environment }}
      service-name: pfh-user-service

      # Custom
      custom-test-script: ./services-functionaliy-test.sh -t unit
      custom-build-script: services-functionaliy-test.sh -t int
    secrets:
      deploy_token: ${{ secrets.DEPLOY_TOKEN }}