name: QA Workflow Services

on:
  workflow_dispatch:
  # Any feature branch PR to QA or direct push to QA will trigger this workflow
  pull_request:
    types:
      - opened       # Trigger PR is first opened
      - reopened     # Trigger PR is reopened 
      - synchronize  # New push where the branch has PR
    branches:
      - qa           # Target branch (base) must be QA
      - 'qa/**'
  push:
    branches:
      - 'qa'
      - 'qa/**'

run-name: "[QA]_[${{ github.event_name }}]: ${{ github.event.head_commit.message || github.event.pull_request.title  }}. at ${{ github.ref_name }} (${{ github.sha }})"

jobs:
  set-configuration:
    name: Setup configuration based on the trigger event
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.determine.outputs.environment }}
      has_open_pr_to_qa: ${{ steps.check_pr.outputs.has_open_pr_to_qa }}
    steps:
      - id: determine
        name: Set environment to QA
        run: |
          echo "environment=QA" >> $GITHUB_OUTPUT
          echo "The matching deployment's environment is QA"

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh
      
      - uses: actions/checkout@v4

      - name: Check if branch has open PR to QA
        id: check_pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          branch="${{ github.ref_name }}"
          pr_count=$(gh pr list --base qa --head "$branch" --state open --json number --jq 'length')
          if [ "$pr_count" -gt 0 ]; then
            echo "has_open_pr_to_qa=true" >> $GITHUB_OUTPUT
          else
            echo "has_open_pr_to_qa=false" >> $GITHUB_OUTPUT
          fi

  # This job will fail if the branch does not have an open PR to QA when triggered manually
  manual-trigger-branch-doest-not-have-pr-to-qa:
    name: Manual trigger on branch that does not have PR to QA
    runs-on: ubuntu-latest
    needs: set-configuration
    if: ${{ github.event_name== 'workflow_dispatch' && needs.set-configuration.outputs.has_open_pr_to_qa == 'false' && github.ref_name != 'qa' && !startsWith(github.ref_name, 'qa/') }} 
    steps:
      - name: Fail the workflow
        run: |
          echo "The branch '${{ github.event.inputs.pull_request_branch }}' does not have an open PR to QA."
          echo "Please create a PR to QA before triggering this workflow manually."
          exit 1

  # This job will run if it's a PR event or if the specified branch has an open PR to QA when triggered manually
  call-pr-ci-workflow:
    name: Pull Request CI Workflow
    needs: set-configuration
    # Only run this job if it's a PR event or if the specified branch has an open PR to QA when triggered manually
    if: ${{ github.event_name== 'pull_request' || (github.event_name== 'workflow_dispatch' && needs.set-configuration.outputs.has_open_pr_to_qa == 'true') }} 
    uses: Le-Hoang-Thinh-The-Automationist/pfh-pipeline/.github/workflows/QA_pull-request-quality-gate.yml@feature/16-infrastructure-pipeline-new-qa-mechanism
    with:
      # Mandatory inputs
      environment: ${{ needs.set-configuration.outputs.environment }}
      service-name: pfh-user-service

      # Custom
      custom-test-script: ./services-functionaliy-test.sh -t unit
      custom-build-script: services-functionaliy-test.sh -t int
    secrets:
      deploy_token: ${{ secrets.DEPLOY_TOKEN }}

  call-merged-commit-ci-workflow:
    name: Quality Monitoring CI workflow
    needs: set-configuration
    if: ${{(github.event_name == 'push')  || (github.event_name == 'workflow_dispatch' && github.ref_name == 'qa' && startsWith(github.ref_name, 'qa/')) }} 
    uses: Le-Hoang-Thinh-The-Automationist/pfh-pipeline/.github/workflows/QA_merged-commit-quality-gate.yml@feature/16-infrastructure-pipeline-new-qa-mechanism
    with:
      # Mandatory inputs
      environment: ${{ needs.set-configuration.outputs.environment }}
      service-name: pfh-user-service

      # Custom
      custom-test-script: ./services-functionaliy-test.sh -t unit
      custom-build-script: services-functionaliy-test.sh -t int
    secrets:
      deploy_token: ${{ secrets.DEPLOY_TOKEN }}